services:
  postgresql:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: managerDb
      POSTGRES_USER: erwinya
      POSTGRES_PASSWORD: 12345678
    ports:
      - 5433:5432
